### ISSUE TITLE
error during conversion

### ISSUE THREAD

**Issue by pixel75** [cjmach/pstconv#37] opened 2024-10-16 19:35 UTC
hi all,
it happens this after a while with a 32G pst file:
```
Unknown message type: REPORT.IPM.Note.NDR
Unknown message type: REPORT.IPM.Note.NDR
java.lang.NullPointerException
        at com.pff.PSTAttachment.getFileInputStream(PSTAttachment.java:123)
        at pt.cjmach.pstconv.PstConverter.getAttachmentBytes(PstConverter.java:484)
        at pt.cjmach.pstconv.PstConverter.convertAttachments(PstConverter.java:444)
        at pt.cjmach.pstconv.PstConverter.convertToMimeMessage(PstConverter.java:349)
        at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:269)
        at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:320)
        at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:320)
        at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:231)
        at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:191)
        at pt.cjmach.pstconv.Launcher.call(Launcher.java:89)
        at pt.cjmach.pstconv.Launcher.call(Launcher.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at pt.cjmach.pstconv.Launcher.main(Launcher.java:104)
```
I'm on win11

any ideas?

**Comment by J0rdyZ65** [comment] 2024-10-30 22:02
Same issue me too. Tried latest snapshot and v0.9.8.
Mine is a 51GB OST file.

```
java.lang.NullPointerException
	at com.pff.PSTAttachment.getFileInputStream(PSTAttachment.java:123)
	at pt.cjmach.pstconv.PstConverter.getAttachmentBytes(PstConverter.java:484)
	at pt.cjmach.pstconv.PstConverter.convertAttachments(PstConverter.java:444)
	at pt.cjmach.pstconv.PstConverter.convertToMimeMessage(PstConverter.java:349)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:269)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:320)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:320)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:320)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:231)
	at pt.cjmach.pstconv.PstConverter.convert(PstConverter.java:191)
	at pt.cjmach.pstconv.Launcher.call(Launcher.java:89)
	at pt.cjmach.pstconv.Launcher.call(Launcher.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at pt.cjmach.pstconv.Launcher.main(Launcher.java:104)
```

**Comment by pixel75** [comment] 2024-10-31 07:45
I confirm that the PST is greater of 32GB. this could be the point. let's try with this I'm not so confident with java so I'll wait your fix :).
thanks

**Comment by J0rdyZ65** [comment] 2024-10-31 12:03
Yep, let’s try it!Thx,G.Il giorno 31 ott 2024, alle ore 02:14, C. Machado Antunes ***@***.***> ha scritto:﻿
Thanks for reporting the issue.
The exception comes from a class belonging to java-libpst library.
What I could see in java-libpst source code (https://github.com/rjohnsondev/java-libpst/blob/master/src/main/java/com/pff/PSTAttachment.java#L123) is that the exception is caused when accessing an item contained in a HashTable defined in parent class PSTObject (https://github.com/rjohnsondev/java-libpst/blob/master/src/main/java/com/pff/PSTObject.java#L123).
The HashTable uses Integers as keys and there are also some casts from long to int when populating that HashTable (https://github.com/rjohnsondev/java-libpst/blob/master/src/main/java/com/pff/PSTTableBC.java#L80).
As you may understand, I'm not the developer of java-libpst library, but I guess there might be some limitation when converting files that are greater than 32 GB in size, and, to be honest, I didn't test pstconv with files that big.
For now, the only solution I can think of is to catch the NullPointerException, report a message to the console and continue with processing the remaining messages. Would this be an acceptable solution for you?

**Comment by cjmach** [comment] 2024-11-03 00:33
Managed to get a PST file with around 39 GB but could not reproduce this issue. For the record, I merged together a bunch of PST files with the Outlook import wizard until it reached that size.
Nevertheless, I pushed the fix that protects against NullPointerException's  and should allow to extract further messages if all goes well. 
I'm going to publish a new release (0.9.9) in the meantime and would really appreciate if you could test it with your own PST files.

Thank you!

**Closed** 2024-11-03 00:37 UTC
Labels: bug

**Comment by pixel75** [comment] 2024-11-04 07:59
I can confirm that v. 0.9.9 is working fine!
thanks
